import './globals.css'
import { Navbar } from '@/components'
import { Footer } from '@/components'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='relative'>
        <Navbar />
          {children}
        <Footer />
      </body>
    </html>
  )
}
